feat(Rows): add icon button as control
Telefonica/mistica-web pull request #1030
Opened 2024-02-21 18:55 UTC by marcoskolodny

Issue: [Link](https://jira.tid.es/browse/WEB-1722)

2024-02-22 10:43 UTC, yceballost requested changes

2024-02-22 10:43 UTC, yceballost commented on src/__stories__/list-story.tsx
> +                        Icon: IconPlayFilled,
```suggestion
                        Icon: IconTrashCanRegular,
```

To let the play/pause icon for toggle example

2024-02-22 10:43 UTC, yceballost commented on src/__stories__/list-story.tsx
> +                        Icon: IconPlayFilled,
```suggestion
                        Icon: IconTrashCanRegular,
```

2024-02-22 11:39 UTC, marcoskolodny commented on src/__stories__/list-story.tsx
> +                        Icon: IconPlayFilled,
discussed offline. No need to make this story more complex. Added `small: false` to make it clear that you can customize it

2024-02-22 11:40 UTC, marcoskolodny commented on src/__stories__/list-story.tsx
Added

2024-02-22 11:43 UTC, yceballost approved these changes

2024-02-22 13:05 UTC, marcoskolodny commented on src/icon-button.tsx
> +    ExclusifyUnion<{'aria-label': string} | {'aria-labelledby': string}>;
forcing aria-label or aria-labelledby

2024-02-23 15:47 UTC, marcoskolodny commented
> once [this one](https://github.com/Telefonica/mistica-web/pull/1034) is merged, should we support `ToggleIconButton` in `Rows` too?

@atabel yes, but that can be a second iteration (in order to avoid blocking this PR)

2024-02-27 09:43 UTC, pladaria commented on src/icon-button.tsx
> +    ExclusifyUnion<{'aria-label': string} | {'aria-labelledby': string}>;
this is a breaking change

2024-03-04 10:36 UTC, pladaria approved these changes

2024-03-04 10:47 UTC, atabel approved these changes

2024-03-04 11:00 UTC, merged

2024-03-13 15:41 UTC, tuentisre commented
:tada: This PR is included in version 14.46.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/14.46.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v14.46.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: