fix(Hero): use background instead of backgroundColor to support gradients
Telefonica/mistica-web pull request #1091
Opened 2024-04-22 13:34 UTC by marcoskolodny

Issue: [Link](https://jira.tid.es/browse/WEB-1822)

2024-04-22 15:07 UTC, atabel commented on src/__screenshot_tests__/__image_snapshots__/hero-screenshot-test-tsx-hero-background-brand-in-o-2-new-skin-1-snap.png
no gradient?

2024-04-22 15:19 UTC, marcoskolodny commented on src/__screenshot_tests__/__image_snapshots__/hero-screenshot-test-tsx-hero-background-brand-in-o-2-new-skin-1-snap.png
Actually, there is a gradient. It's just not very noticeable. If I pick the topmost color in a color picker tool online, I get this:

![image](https://github.com/Telefonica/mistica-web/assets/25785151/9908783c-4d77-49d6-bb88-30dd9f5e6358)

While the lowest one is this:

![image](https://github.com/Telefonica/mistica-web/assets/25785151/41c6d0f3-fa07-405d-90d9-24cd4eba95b0)

2024-04-22 18:32 UTC, pladaria approved these changes

2024-04-22 20:20 UTC, yceballost requested changes

2024-04-22 20:20 UTC, yceballost commented on src/__screenshot_tests__/__image_snapshots__/hero-screenshot-test-tsx-hero-background-brand-in-o-2-new-skin-1-snap.png
The problem here is that the gradient is starting in the top of the component, the background only have to cover the part of the content to show the gradient correctly

![image](https://github.com/Telefonica/mistica-web/assets/6722153/d91fff69-9657-4f38-b4ef-e070041459ca)

@aweell are u agree? or can you see any problem?

2024-04-23 10:12 UTC, marcoskolodny commented on src/__screenshot_tests__/__image_snapshots__/hero-screenshot-test-tsx-hero-background-brand-in-o-2-new-skin-1-snap.png
I've fixed this issue. Now it should look better :)

2024-04-23 10:28 UTC, yceballost approved these changes

2024-04-23 14:42 UTC, atabel approved these changes

2024-04-23 14:52 UTC, merged

2024-05-06 16:06 UTC, tuentisre commented
:tada: This PR is included in version 15.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/15.4.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v15.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: