feat(Chip): allow using badge in selectable chips
Telefonica/mistica-web pull request #1134
Opened 2024-05-30 18:42 UTC by marcoskolodny

Issue: [Link](https://jira.tid.es/browse/WEB-1880)
Closes https://github.com/Telefonica/mistica-web/issues/1123

2024-05-30 21:02 UTC, yceballost requested changes

2024-05-30 21:02 UTC, yceballost commented on src/__screenshot_tests__/__image_snapshots__/private-skin-components-screenshot-test-tsx-components-in-blau-1-snap.png
Imo, we should remove active status from one of the two chips (or include a new chip without active status to have this test)

2024-05-31 07:05 UTC, atabel approved these changes

2024-05-31 14:07 UTC, marcoskolodny commented on src/__screenshot_tests__/__image_snapshots__/private-skin-components-screenshot-test-tsx-components-in-blau-1-snap.png
done

2024-06-03 13:33 UTC, pladaria approved these changes

2024-06-04 15:09 UTC, yceballost approved these changes

2024-06-04 15:47 UTC, merged

2024-06-19 10:00 UTC, tuentisre commented
:tada: This PR is included in version 15.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/15.11.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v15.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: