feat(Form fields): improve accesibility of errors
Telefonica/mistica-web pull request #1246
Opened 2024-09-18 10:50 UTC by atabel

WEB-1958

2024-09-19 11:13 UTC, atabel commented on src/credit-card-expiration-field.tsx
> -        }
I've find this code repeated in most input fields, I've moved it inside `useFieldProps`

2024-09-19 11:15 UTC, atabel commented on src/form-context.tsx
> +        inputRef: (input: HTMLInputElement | null) => register(name, {input, validator: validate, label}),
I need the field label to be in the registrations map, to be able to use it when rendering the global form error: "Revisa los errores en los siguientes campos: nombre, email"

2024-09-19 11:18 UTC, atabel commented on src/text-field-base.tsx
> +                    )}
Moved the label before the input. This avoids a bug (I think it's a bug) in Safari/VoiceOver which made the label being read twice by screen reader (when focusing the input, and then as an independent element). This doesn't happen if the label appears before the input in the html.

2024-09-19 11:27 UTC, atabel commented on src/cvv-field.tsx
> -                            )
![image](https://github.com/user-attachments/assets/8b23d97b-2522-4877-adb0-a8a63bef9dac)

2024-09-19 14:08 UTC, yceballost requested changes

2024-09-19 14:08 UTC, yceballost commented on src/__screenshot_tests__/__image_snapshots__/form-select-screenshot-test-tsx-select-error-1-snap.png
in desktop, the text is not aligned in the same way as mobile, @aweell is this expected? 

is it possible to align the text line to the middle of the icon? (compare with mobile screenshot to see the difference)
<img width="390" alt="image" src="https://github.com/user-attachments/assets/721bd27b-62b0-4cb1-a747-37b2944f9f90">

2024-09-19 19:36 UTC, aweell commented on src/__screenshot_tests__/__image_snapshots__/form-select-screenshot-test-tsx-select-error-1-snap.png
Not expected, but also not correctly documented in the specs


the size of the icon could be 1lh to match the line height in mobile (16) but also in desktop (20) so even if the font-size increases appears aligned to the first line of text? this approach seems correct?

2024-09-20 12:59 UTC, pladaria commented on src/__tests__/form-test.tsx
> +test('when there are multiple errors on submit, the fields with error are anounced by screen reader', async () => {
what happens when multiple fields contain errors? All errors gets announced?

If so, can you add a test for this case?

2024-09-20 13:48 UTC, pladaria approved these changes

2024-09-24 11:22 UTC, atabel commented on src/text-field-components.tsx
> +                            <IconInformationRegular size="1rem" color={leftColor} />
fixed

2024-09-24 11:22 UTC, atabel commented on src/__screenshot_tests__/__image_snapshots__/form-select-screenshot-test-tsx-select-error-1-snap.png
changed size to `1lh` (fallback to 1rem for old browsers not supporting `lh` unit)

2024-09-25 08:39 UTC, aweell approved these changes
LGTM!

2024-09-25 10:02 UTC, marcoskolodny approved these changes

2024-09-26 16:13 UTC, yceballost approved these changes

2024-09-26 16:35 UTC, merged

2024-09-27 13:33 UTC, tuentisre commented
:tada: This PR is included in version 16.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/16.1.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v16.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: