chore(tokens): sync design tokens
Telefonica/mistica-web pull request #1288
Opened 2024-11-06 11:31 UTC by pladaria

2024-11-06 13:19 UTC, yceballost commented on css/vivo-new.css
Care, these changes should be released "together" with native releases

2024-11-06 13:26 UTC, yceballost requested changes

2024-11-06 13:26 UTC, yceballost commented on css/vivo-new.css
you also need to import the new font weight

you can get the font in this jira ticket
https://jira.tid.es/browse/OBVIVO-2687

Download de zip and replace all VivoType fonts (not only medium). All fonts have minor changes in metadata

2024-11-08 08:14 UTC, atabel approved these changes

2024-11-08 09:22 UTC, marcoskolodny approved these changes

2024-11-08 09:49 UTC, yceballost commented on css/vivo-new.css
I added the zip in this jira

2024-11-08 10:05 UTC, pladaria commented on css/vivo-new.css
I've reverted the imported changes

2024-11-08 10:28 UTC, yceballost approved these changes

2024-11-08 10:39 UTC, merged

2024-11-18 10:33 UTC, tuentisre commented
:tada: This PR is included in version 16.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/16.5.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v16.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: