feat(Rows,Cards): change title font weight from light to regular
Telefonica/mistica-web pull request #244
Opened 2021-04-21 13:35 UTC by yceballost

We changed titles weight from Light to Regular in certain components:
- Rowlist
- Cards
- Highligted card
- Emtpy state card

Ticket: https://jira.tid.es/browse/WEB-235

2021-06-08 17:13 UTC, pladaria commented on src/card.tsx
> -                                <Text4 as="h1" light>
you must re-generate affected screenshot tests

from the repo root:
    yarn test-acceptance -u

then commit and push the result

2021-06-08 17:14 UTC, pladaria requested changes
please, regenerate screenshot tests

from the repo root:
```
yarn test-acceptance -u
```
then commit and push the result

2021-06-08 17:33 UTC, yceballost commented
> please, regenerate screenshot tests
> 
> from the repo root:
> 
> first make sure you're updated with master your deps are up to date:
> 
> ```
> git fetch
> git merge origin/master
> (commit / push)
> yarn
> ```
> 
> then run the tests updating the snapshots:
> 
> ```
> yarn test-acceptance -u
> ```
> 
> then commit and push the result

I'm getting this error

![image](https://user-images.githubusercontent.com/6722153/121231214-704ef280-c890-11eb-914d-32faf14efaa2.png)

2021-06-09 09:31 UTC, pladaria commented
> I'm getting this error

You need to install docker and docker compose

If you don't want to, I can update the screenshots for you

2021-06-09 09:39 UTC, yceballost commented
> install docker and docker compose

I already done!

2021-06-09 11:57 UTC, pladaria approved these changes
Good job!

Remember to disable docker while you're not using it, otherwise it will waste your mac resources.

2021-06-09 15:40 UTC, atabel approved these changes
Not sure why the placeholder border color changed :/
![image](https://user-images.githubusercontent.com/1849576/121385901-d2b7f980-c949-11eb-9336-c13dee0d3a66.png)

2021-06-09 16:14 UTC, merged

2021-06-16 11:30 UTC, tuentisre commented
:tada: This PR is included in version 9.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/9.5.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v9.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: