feat(MasterDetailLayout): new component
Telefonica/mistica-web pull request #301
Opened 2021-07-15 13:17 UTC by atabel

jira ticket: WEB-276

2021-07-15 14:19 UTC, pladaria approved these changes

2021-07-15 14:22 UTC, yceballost requested changes
- Missing Grid Layout 4+6 in Storybook

Why do you create masterDetailLayout instead of include all the logic directly in GridLayout template="4+6"?

2021-07-15 16:12 UTC, atabel commented
> * Missing Grid Layout 4+6 in Storybook
> 
That will be done in a different PR
> Why do you create masterDetailLayout instead of include all the logic directly in GridLayout template="4+6"?
Because that would add additional logic to the `GridLayout` component, and we prefer to keep it focused in just the columns layout. Also, you may want a 4+6 layout without the logic of `MasterDetail` (two navigation levels in mobile). Pedro and I discussed that possibility, I paste here part of that conversation:
![image](https://user-images.githubusercontent.com/1849576/125820861-777e1a86-ffff-4979-b83d-fc75ae381447.png)
![image](https://user-images.githubusercontent.com/1849576/125821169-076a85ce-c948-4067-bc7d-7db262393196.png)

2021-07-15 16:16 UTC, atabel commented
I've completed the layout doc with this new component: https://github.com/Telefonica/mistica-web/blob/atoledano-master-detail/doc/layout.md#masterdetaillayout

2021-07-16 09:15 UTC, pladaria approved these changes

2021-07-16 15:11 UTC, anabelengp approved these changes

2021-07-19 12:49 UTC, yceballost commented
> > * Missing Grid Layout 4+6 in Storybook
> 
> Ok, I'll add it
> 
> > Why do you create masterDetailLayout instead of include all the logic directly in GridLayout template="4+6"?
> 
> Because that would add additional logic to the `GridLayout` component, and we prefer to keep it focused in just the columns layout. Also, you may want a 4+6 layout without the logic of `MasterDetail` (two navigation levels in mobile). Pedro and I discussed that possibility, I paste here part of that conversation:
> ![image](https://user-images.githubusercontent.com/1849576/125820861-777e1a86-ffff-4979-b83d-fc75ae381447.png)
> ![image](https://user-images.githubusercontent.com/1849576/125821169-076a85ce-c948-4067-bc7d-7db262393196.png)

check this @HectorSancho

2021-07-20 13:21 UTC, yceballost requested changes
I think would be nice to add a vertical divider between "areas" like in this design
![image](https://user-images.githubusercontent.com/6722153/126331265-07dd4ae1-c22c-43f4-903e-a46a1c083ab1.png)

2021-07-20 13:44 UTC, atabel commented
> I think would be nice to add a vertical divider between "areas" like in this design

That can be done inside `master` view if needed, I wouldn't include that inside the `MasterDetailLayout`

2021-07-20 13:52 UTC, atabel commented
I've included the 6+4 layout in this PR too

2021-07-20 13:54 UTC, atabel commented on playroom/use-scope.tsx
> +        ...screenSize,
@pladaria, this allows us to create playrooms using `isMobile`, `isTabletOrBigger`, etc

2021-07-20 14:07 UTC, HectorSancho approved these changes

2021-07-20 14:31 UTC, yceballost approved these changes

2021-07-20 15:43 UTC, pladaria approved these changes

2021-07-20 16:19 UTC, merged

2021-07-23 13:27 UTC, tuentisre commented
:tada: This PR is included in version 9.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/9.10.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v9.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: