WEB - 443 - Update Feedback icons for O2.
Telefonica/mistica-web pull request #402
Opened 2022-01-25 15:24 UTC by RubenMorPov

[WEB - 443](https://jira.tid.es/browse/WEB-443)

- Updated the success feedback icon for O2 to remove padding.
- Changed error feedback icon for O2.
- Changed info feedback icon for O2.

2022-01-25 16:27 UTC, yceballost requested changes

2022-01-26 09:19 UTC, pladaria commented
This icon now has cropped edges 
![image](https://user-images.githubusercontent.com/579417/151136159-cce7434d-a2ce-4856-9db4-86f26cd53be8.png)

2022-01-26 09:30 UTC, RubenMorPov commented on src/icons/icon-error.tsx
>                      <path
I think is solved now. I used the new ones, but added strokeWith on the exclamation dots. I removed it, so it looks thin. 😄

2022-01-26 11:14 UTC, yceballost approved these changes
perfect!

2022-01-26 12:36 UTC, pladaria reviewed
No changes in screenshot tests?

2022-01-27 11:28 UTC, atabel commented
> No changes in screenshot tests?

I think we only have screenshots for Movistar

2022-01-27 13:46 UTC, atabel approved these changes

2022-02-15 15:14 UTC, pladaria approved these changes

2022-02-15 16:20 UTC, merged

2022-02-15 17:41 UTC, tuentisre commented
:tada: This PR is included in version 10.24.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/10.24.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v10.24.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: