feat(SnapCard): new component
Telefonica/mistica-web pull request #487
Opened 2022-06-07 10:56 UTC by atabel

jira: WEB-446

2022-06-07 16:08 UTC, yceballost requested changes

2022-06-08 08:54 UTC, atabel commented on flow-defs/card.js.flow
> +  icon?: React.Element<any>,
I used the same prop name we use in other card components

2022-06-09 09:38 UTC, RubenMorPov approved these changes

2022-06-09 16:11 UTC, yceballost commented on flow-defs/card.js.flow
> +  icon?: React.Element<any>,
but it is quite weird use 🤔

```
icon={
        <Image
          src="https://i.imgur.com/aEVtKsE.jpg"
          height={64}
          aspectRatio="16:9"
        />
      }
```

if you think is ok, you can solve this comment

2022-06-10 12:21 UTC, atabel commented on flow-defs/card.js.flow
> +  icon?: React.Element<any>,
I prefer to be consistent in components api

2022-06-14 13:33 UTC, yceballost approved these changes

2022-06-14 15:22 UTC, pladaria commented on src/card.tsx
> +const useSnapCardStyles = createUseStyles((theme) => ({
why don't define this component in its own file? (snap-card.tsx)

2022-06-14 15:25 UTC, pladaria approved these changes

2022-06-15 07:35 UTC, aweell approved these changes

2022-06-15 08:06 UTC, RubenMorPov approved these changes

2022-06-15 10:57 UTC, atabel commented on src/card.tsx
> +                <Touchable maybe {...touchableProps} className={classes.touchable} aria-label={ariaLabel}>
I don't think is a good idea. If no ariaLabel is provided, screen readers will read the text inside the button/a as the label: the title and subtitle.

2022-06-15 10:58 UTC, merged

2022-06-20 08:45 UTC, tuentisre commented
:tada: This PR is included in version 11.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/11.11.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v11.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: