feat(General): multiple style changes in components and color changes in Movistar skin
Telefonica/mistica-web pull request #497
Opened 2022-06-22 13:36 UTC by atabel

2022-06-23 06:29 UTC, yceballost commented on src/skins/types.tsx
> +    // brandHigh: string;
why this comment?

2022-06-23 07:12 UTC, atabel commented on src/skins/types.tsx
> +    // brandHigh: string;
leftovers, I'll remove it

2022-06-23 13:43 UTC, yceballost requested changes

2022-06-23 13:43 UTC, yceballost commented on src/skins/movistar.tsx
>              neutralMedium: palette.grey5,
neutralLow wrong color, change to `grey1`
https://github.com/Telefonica/mistica-design/blob/f823f0765e6e8491e883a2e7019a736e1206a359/tokens/movistar.json#L299

2022-06-23 13:43 UTC, yceballost commented on src/skins/o2.tsx
>              neutralMedium: palette.grey5,
neutralLow → `grey1`
https://github.com/Telefonica/mistica-design/blob/f823f0765e6e8491e883a2e7019a736e1206a359/tokens/o2.json#L298

2022-06-23 13:43 UTC, yceballost commented on src/skins/o2-classic.tsx
>              neutralLow: palette.grey3,
neutralLow → `grey1`
https://github.com/Telefonica/mistica-design/blob/f823f0765e6e8491e883a2e7019a736e1206a359/tokens/classic-o2.json#L298

2022-06-23 13:43 UTC, yceballost commented on src/skins/vivo.tsx
>              neutralMedium: palette.grey5,
neutralLow → `grey1`
https://github.com/Telefonica/mistica-design/blob/f823f0765e6e8491e883a2e7019a736e1206a359/tokens/vivo.json#L299

2022-06-23 13:43 UTC, yceballost commented on src/skins/blau.tsx
>              neutralMedium: palette.grey5,
neutralLow → `grey1`
https://github.com/Telefonica/mistica-design/blob/f823f0765e6e8491e883a2e7019a736e1206a359/tokens/vivo.json#L299

2022-06-23 17:39 UTC, yceballost commented
I forgot to put in jira ticket that Empty State component also change the description to regular weight
![image](https://user-images.githubusercontent.com/6722153/175360952-efa7632f-3aeb-4327-b7a4-2853b46d52e1.png)

2022-06-28 14:11 UTC, pladaria approved these changes

2022-06-28 15:35 UTC, yceballost approved these changes
superb! <3

2022-06-30 17:16 UTC, yceballost commented
I found a bug between actual versions and this PR
![image](https://user-images.githubusercontent.com/6722153/176738147-c504ddd8-ecd7-4d7a-9b73-8e48c1e6ddcd.png)

https://ibit.ly/09Ja

Maybe is the same bug found in screenshots WEB-596

2022-08-04 07:35 UTC, merged

2022-08-04 07:38 UTC, tuentisre commented
:tada: This PR is included in version 12.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/12.0.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v12.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: