feat(DataCard, MediaCard): remove extra top padding
Telefonica/mistica-web pull request #621
Opened 2022-12-16 14:08 UTC by atabel

2022-12-19 11:48 UTC, yceballost requested changes

2022-12-19 11:48 UTC, yceballost commented on src/card.tsx
> -            <Stack space={16}>
remove extra padding in snap card too, please!

2022-12-21 07:46 UTC, sergivillar approved these changes

2022-12-27 15:31 UTC, yceballost approved these changes
Remember when you update Webapp with this new version add in all of extra prop, a Box with paddingTop={16} to avoid breaking visual changes

2022-12-28 09:10 UTC, merged

2022-12-28 10:27 UTC, tuentisre commented
:tada: This PR is included in version 13.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/13.0.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v13.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: