feat[PTIECBC03-3631]: inverse progress bar
Telefonica/mistica-web pull request #704
Opened 2023-03-30 15:03 UTC by BrunoGuimaraes103

Addition of inverted animation option in the progress-bar component, according to Figma:
https://www.figma.com/file/4INjJeoqC7elguwiwg6PqH/Progress-Bar?node-id=0-1&t=fbTFrVoBerKk1vjK-0

2023-03-31 07:13 UTC, atabel commented
Are this changes already in the figma Design specs, @yceballost?

2023-03-31 14:03 UTC, AlexJCelmer commented
Hello, follow the discussion link with the approval of moving the component to development

https://github.com/Telefonica/mistica-design/issues/1116

2023-03-31 17:30 UTC, yceballost commented
> Are this changes already in the figma Design specs, @yceballost? I see the linked figma is just a proposal

This change is approved by mistica design team, made by vivo design team and included in official mística progrss bar specs.

It is important to work on this evolution using the official specs document to avoid problems in reviews. Vivo design team has to avoid the creation of this parallel specs, or avoid to share with development team.

This is the source of truth for this component
https://www.figma.com/file/3IO1EsGDeBRiFdF23mrvuj/%F0%9F%94%B8-ProgressBar-Specs?node-id=0%3A1&t=eYIOKRVqERQzStn0-1

2023-03-31 17:32 UTC, yceballost requested changes

2023-03-31 17:32 UTC, yceballost commented on src/progress-bar.tsx
> +    inverse = false,
Don't use 'inverse' for this prop, this name cause conflicts between `inverse` prop in other component that shows inverse state (for color backgrounds)

alternatives...
- inverted?
- animationInverted?

@atabel wdyt?

2023-04-13 14:36 UTC, atabel commented on src/progress-bar.tsx
> +    inverted = false,
rename to `reverse` please

2023-04-14 06:45 UTC, atabel approved these changes

2023-04-14 06:54 UTC, merged

2023-04-17 07:42 UTC, tuentisre commented
:tada: This PR is included in version 14.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/14.5.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v14.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: