feat(skin): make border radius configurable by skin. Change border radius from 8 to 16 in boxed components in some skins
Telefonica/mistica-web pull request #723
Opened 2023-04-20 12:51 UTC by atabel

2023-04-20 16:50 UTC, brtbrt commented on src/skins/telefonica.tsx
> +        borderRadii: {
it's the plural 🌝

2023-04-20 21:42 UTC, yceballost requested changes

2023-04-20 21:42 UTC, yceballost commented on src/progress-bar.css.ts
> +    borderRadius: vars.borderRadii.indicator,
```suggestion
    borderRadius: vars.borderRadii.bar,
```

2023-04-20 21:42 UTC, yceballost commented on src/progress-bar.css.ts
> +    borderRadius: vars.borderRadii.indicator,
```suggestion
    borderRadius: vars.borderRadii.bar,
```

2023-04-20 21:42 UTC, yceballost commented on src/stepper.css.ts
> +        borderRadius: skinVars.borderRadii.indicator,
```suggestion
        borderRadius: skinVars.borderRadii.bar,
```

2023-04-20 21:42 UTC, yceballost commented on src/stepper.css.ts
> +        borderRadius: skinVars.borderRadii.indicator,
```suggestion
        borderRadius: skinVars.borderRadii.bar,
```

2023-04-21 06:51 UTC, atabel commented on src/skins/telefonica.tsx
> +        borderRadii: {
we have `colors` (plural of color), so it makes sense to use `borderRadii` (plural of borderRadius) here

2023-04-21 06:52 UTC, atabel commented on src/sprinkles.css.ts
> +        borderRadius: ['50%', 2, 4, 8, 16, 20, ...Object.values(vars.borderRadii)],
no, the css vars that vanilla extracts generates for those

2023-04-21 12:52 UTC, brtbrt approved these changes

2023-04-21 16:59 UTC, yceballost commented on src/skins/telefonica.tsx
> +        borderRadii: {
🤯

2023-04-21 17:00 UTC, yceballost approved these changes

2023-04-24 08:06 UTC, AnaMontes11 approved these changes
Great job! ✨

2023-04-24 08:49 UTC, marcoskolodny approved these changes

2023-04-24 09:01 UTC, merged

2023-04-27 15:16 UTC, tuentisre commented
:tada: This PR is included in version 14.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/14.7.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v14.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: