feat(Cards): add interactivity to cards
Telefonica/mistica-web pull request #763
Opened 2023-05-23 15:05 UTC by marcoskolodny

- Add OnPress to every card ([Issue](https://jira.tid.es/browse/WEB-831))
- Update hover/active styles for every card and top actions
- Fix bug with small display/poster cards ([Issue](https://jira.tid.es/browse/WEB-1388))
- Remove border of cards in every case, except when card is default over default

2023-06-02 16:35 UTC, yceballost submitted a review, later dismissed

2023-06-02 16:35 UTC, yceballost commented on src/__screenshot_tests__/__image_snapshots__/poster-card-screenshot-test-tsx-poster-card-closable-1-snap.png
missing onpress prop in poster story and playroom, can you include it? 

Also, a bug is appear when you include onPress in Poster
https://tinyurl.com/2eqpou7k

2023-06-02 17:02 UTC, marcoskolodny commented on src/__screenshot_tests__/__image_snapshots__/poster-card-screenshot-test-tsx-poster-card-closable-1-snap.png
fixed :)

2023-06-05 08:16 UTC, yceballost requested changes

2023-06-05 08:16 UTC, yceballost commented on src/__stories__/media-card-story.tsx
Bug behavior only in O2 classic

https://github.com/Telefonica/mistica-web/assets/6722153/61d3f814-c654-4460-adf6-7a2093ed8073

https://tinyurl.com/2edqbnz9

2023-06-05 08:16 UTC, yceballost commented on src/__screenshot_tests__/__image_snapshots__/poster-card-screenshot-test-tsx-poster-card-closable-1-snap.png
still missing `onPress` in playroom snippets 👀 (add it to snap card too)

2023-06-05 08:21 UTC, aweell requested changes
I've just updated the definition for top actions default state since they should be transparent in all cases unless they're on top of media:

### Over default containers

|Element | State | Token / Color | 
| ------- | ----- | ----- |
| container | default | `transparent` | 
| container | :hover | `backgroundContainerHover` | 
| container | :active/pressed | `backgroundContainerPressed` | 
| icon | all | `neutralHigh` |

### Over inverse containers

|Element | State | Token / Color | 
| -----| ----- | ----- |
| container | default | `transparent` | 
| container | :hover | `backgroundContainerBrandHover` | 
| container | :active/pressed | `backgroundContainerBrandPressed` | 
| icon | all | `inverse` | 

### Over media elements

| Element | State | Token / Color | Alpha |
| -----| ----- | ----- | ----- |
| container | default | `inverse` | 70% |
| container | :hover | `inverse` | 90% |
| container | :active/pressed | `inverse` | 100% |
| icon | all | `#000000` | - |

This change will avoid the cases where the card is hovered or pressed or the container is using `backgroundContainerBrandOverInverse`:


![Screenshot 2023-06-05 at 09 38 03](https://github.com/Telefonica/mistica-web/assets/44420072/5cefc123-1e17-4776-abb9-cad22ecd1c49)
![Screenshot 2023-06-05 at 09 38 40](https://github.com/Telefonica/mistica-web/assets/44420072/9f8cc00f-b107-4c94-b03e-ab6056865459)

2023-06-05 08:46 UTC, marcoskolodny commented on src/__screenshot_tests__/__image_snapshots__/poster-card-screenshot-test-tsx-poster-card-closable-1-snap.png
does it make sense to add a snippet in playroom only for onPress? We don't have snippets for other scenarios, like button/link actions

2023-06-05 09:01 UTC, marcoskolodny commented on src/__stories__/media-card-story.tsx
This is because O2 Classic skin is deprecated. After discussing offline, we decided to ignore this scenario instead of keeping the deprecated skin up to date by hand.

2023-06-05 17:03 UTC, yceballost approved these changes
✨

2023-06-06 07:24 UTC, aweell approved these changes

2023-06-06 13:28 UTC, atabel commented on src/card.tsx
> +const MaybeWithActions = ({actions, onClose, type}: MaybeWithActionsProps): JSX.Element => {
I'd rename this component. `MaybeWithActions` was a good name when it was a wrapper that received a children. You could even remove the component and move all this logic inside `CardActionsGroup`

2023-06-06 13:28 UTC, atabel commented on src/card.tsx
> +                        {isTouchable && <div className={overlayStyle} style={{zIndex: 1}} />}
can't this zIndex be part of `overlayStyle` ?

2023-06-07 10:08 UTC, marcoskolodny commented on src/card.css.ts
> +                transition: 'all 0.1s',
this was old logic. Good catch

2023-06-08 13:20 UTC, atabel approved these changes

2023-06-08 13:29 UTC, merged

2023-06-15 12:58 UTC, tuentisre commented
:tada: This PR is included in version 14.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@telefonica/mistica/v/14.14.0)
- [GitHub release](https://github.com/Telefonica/mistica-web/releases/tag/v14.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: